Adding all reports

diff --git a/.github/workflows/fossology_integration.yml b/.github/workflows/fossology_integration.yml
--- a/.github/workflows/fossology_integration.yml
+++ b/.github/workflows/fossology_integration.yml
@@ -164,6 +164,166 @@ jobs:
             echo "Max retries reached. Unable to download the report."
             exit 1
           fi
+      - name: GENERATE readmeoss REPORT
+        run: |
+          FOSSY_READMEOSS_RESPONSE=$( \
+          curl -v --location '${{ secrets.FOSSY_BASE_URL }}/api/v1/report' \
+          --header 'Authorization: ${{ env.FOSSY_BEARER_TOKEN }}' \
+          --header 'reportFormat: readmeoss' \
+          --header 'uploadId: ${{ env.FOSSY_UPLOAD_ID }}' \
+          )
+          echo FOSSY_READMEOSS_RESPONSE="$FOSSY_READMEOSS_RESPONSE" >> $GITHUB_ENV
+      - name: GET readmeoss REPORT URL
+        run: |
+          FOSSY_READMEOSS_REPORT_URL=$( \
+          echo $FOSSY_READMEOSS_RESPONSE | jq -r '.message' \
+          )
+          echo FOSSY_READMEOSS_REPORT_URL="$FOSSY_READMEOSS_REPORT_URL" >> $GITHUB_ENV
+      - name: DOWNLOAD readmeoss REPORT
+        run: |
+          max_retries=5
+          retries=0
+
+          while [ $retries -lt $max_retries ]; do
+            response_code=$( \
+            curl -s -o public/readmeoss.md -w "%{http_code}" --location '${{ env.FOSSY_READMEOSS_REPORT_URL }}' \
+            --header 'Authorization: ${{ env.FOSSY_BEARER_TOKEN }}' \
+            )
+            
+            if [ "$response_code" = "200" ]; then
+              echo "Response code is $response_code. Downloading..."
+              break
+            else
+              echo "Response code is $response_code. Retrying in 60 Seconds..."
+              sleep 60  # Wait for 60 seconds before the next iteration
+              retries=$((retries + 1))
+            fi
+          done
+
+          if [ $retries -eq $max_retries ]; then
+            echo "Max retries reached. Unable to download the report."
+            exit 1
+          fi
+      - name: GENERATE spdx2 REPORT
+        run: |
+          FOSSY_SPDX2_RESPONSE=$( \
+          curl -v --location '${{ secrets.FOSSY_BASE_URL }}/api/v1/report' \
+          --header 'Authorization: ${{ env.FOSSY_BEARER_TOKEN }}' \
+          --header 'reportFormat: spdx2' \
+          --header 'uploadId: ${{ env.FOSSY_UPLOAD_ID }}' \
+          )
+          echo FOSSY_SPDX2_RESPONSE="$FOSSY_SPDX2_RESPONSE" >> $GITHUB_ENV
+      - name: GET spdx2 REPORT URL
+        run: |
+          FOSSY_SPDX2_REPORT_URL=$( \
+          echo $FOSSY_SPDX2_RESPONSE | jq -r '.message' \
+          )
+          echo FOSSY_SPDX2_REPORT_URL="$FOSSY_SPDX2_REPORT_URL" >> $GITHUB_ENV
+      - name: DOWNLOAD spdx2 REPORT
+        run: |
+          max_retries=5
+          retries=0
+
+          while [ $retries -lt $max_retries ]; do
+            response_code=$( \
+            curl -s -o public/spdx2.spdx.rdf -w "%{http_code}" --location '${{ env.FOSSY_SPDX2_REPORT_URL }}' \
+            --header 'Authorization: ${{ env.FOSSY_BEARER_TOKEN }}' \
+            )
+            
+            if [ "$response_code" = "200" ]; then
+              echo "Response code is $response_code. Downloading..."
+              break
+            else
+              echo "Response code is $response_code. Retrying in 60 Seconds..."
+              sleep 60  # Wait for 60 seconds before the next iteration
+              retries=$((retries + 1))
+            fi
+          done
+
+          if [ $retries -eq $max_retries ]; then
+            echo "Max retries reached. Unable to download the report."
+            exit 1
+          fi
+      - name: GENERATE unifiedreport REPORT
+        run: |
+          FOSSY_UNIFIEDREPORT_RESPONSE=$( \
+          curl -v --location '${{ secrets.FOSSY_BASE_URL }}/api/v1/report' \
+          --header 'Authorization: ${{ env.FOSSY_BEARER_TOKEN }}' \
+          --header 'reportFormat: unifiedreport' \
+          --header 'uploadId: ${{ env.FOSSY_UPLOAD_ID }}' \
+          )
+          echo FOSSY_UNIFIEDREPORT_RESPONSE="$FOSSY_UNIFIEDREPORT_RESPONSE" >> $GITHUB_ENV
+      - name: GET unifiedreport REPORT URL
+        run: |
+          FOSSY_UNIFIEDREPORT_REPORT_URL=$( \
+          echo $FOSSY_UNIFIEDREPORT_RESPONSE | jq -r '.message' \
+          )
+          echo FOSSY_UNIFIEDREPORT_REPORT_URL="$FOSSY_UNIFIEDREPORT_REPORT_URL" >> $GITHUB_ENV
+      - name: DOWNLOAD unifiedreport REPORT
+        run: |
+          max_retries=5
+          retries=0
+
+          while [ $retries -lt $max_retries ]; do
+            response_code=$( \
+            curl -s -o public/unifiedreport.docx -w "%{http_code}" --location '${{ env.FOSSY_UNIFIEDREPORT_REPORT_URL }}' \
+            --header 'Authorization: ${{ env.FOSSY_BEARER_TOKEN }}' \
+            )
+            
+            if [ "$response_code" = "200" ]; then
+              echo "Response code is $response_code. Downloading..."
+              break
+            else
+              echo "Response code is $response_code. Retrying in 60 Seconds..."
+              sleep 60  # Wait for 60 seconds before the next iteration
+              retries=$((retries + 1))
+            fi
+          done
+
+          if [ $retries -eq $max_retries ]; then
+            echo "Max retries reached. Unable to download the report."
+            exit 1
+          fi
+      - name: GENERATE decisionexporter REPORT
+        run: |
+          FOSSY_DECISION_EXPORTER_RESPONSE=$( \
+          curl -v --location '${{ secrets.FOSSY_BASE_URL }}/api/v1/report' \
+          --header 'Authorization: ${{ env.FOSSY_BEARER_TOKEN }}' \
+          --header 'reportFormat: decisionexporter' \
+          --header 'uploadId: ${{ env.FOSSY_UPLOAD_ID }}' \
+          )
+          echo FOSSY_DECISION_EXPORTER_RESPONSE="$FOSSY_DECISION_EXPORTER_RESPONSE" >> $GITHUB_ENV
+      - name: GET decisionexporter REPORT URL
+        run: |
+          FOSSY_DECISION_EXPORTER_REPORT_URL=$( \
+          echo $FOSSY_DECISION_EXPORTER_RESPONSE | jq -r '.message' \
+          )
+          echo FOSSY_DECISION_EXPORTER_REPORT_URL="$FOSSY_DECISION_EXPORTER_REPORT_URL" >> $GITHUB_ENV
+      - name: DOWNLOAD decisionexporter REPORT
+        run: |
+          max_retries=5
+          retries=0
+
+          while [ $retries -lt $max_retries ]; do
+            response_code=$( \
+            curl -s -o public/decisionexporter.json -w "%{http_code}" --location '${{ env.FOSSY_DECISION_EXPORTER_REPORT_URL }}' \
+            --header 'Authorization: ${{ env.FOSSY_BEARER_TOKEN }}' \
+            )
+            
+            if [ "$response_code" = "200" ]; then
+              echo "Response code is $response_code. Downloading..."
+              break
+            else
+              echo "Response code is $response_code. Retrying in 60 Seconds..."
+              sleep 60  # Wait for 60 seconds before the next iteration
+              retries=$((retries + 1))
+            fi
+          done
+
+          if [ $retries -eq $max_retries ]; then
+            echo "Max retries reached. Unable to download the report."
+            exit 1
+          fi
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v1
         with:
